Networking\InitCmsBundle\Entity\GalleryView:
  type: entity
  table: gallery_view
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    galleryType:
      type: string
      length: 50
      column: gallery_type
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
  manyToOne:
    mediaGallery:
      targetEntity: Networking\InitCmsBundle\Entity\Gallery
      cascade: ["merge"]
      joinColumn:
        name: media_gallery_id
        onDelete: 'CASCADE'