Networking\InitCmsBundle\Entity\Media:
  type: entity
  table: media__media
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    locale:
      type: string
      length: 6
      nullable: true
  oneToMany:
    galleryHasMedias:
      targetEntity: Networking\InitCmsBundle\Entity\GalleryHasMedia
      mappedBy: media
      orphan-removal: true
  manyToMany:
    tags:
      targetEntity: Networking\InitCmsBundle\Entity\Tag
      joinTable:
        name: media_tags
        joinColumns:
          media_id:
            referencedColumnName: id
            onDelete: 'CASCADE'
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
            onDelete: 'CASCADE'
  lifecycleCallbacks:
    prePersist: [ prePersist ]
    preUpdate: [ preUpdate ]

