imports:
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/doctrine_orm_admin.xml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/security_config.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/fos_user.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_admin.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_block.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_media.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/sonata_user.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/stof_doctrine_extensions.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/symfony_cmf_routing_extra.yml }
#    - { resource: @ApplicationSonataMediaBundle/Resources/config/doctrine_orm_admin.xml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/cms/mopa_bootstrap.yml }
    - { resource: @MopaRemoteUpdateBundle/Resources/config/config.yml }

