sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
           GUEST:    [VIEW, LIST]
           STAFF:    [EDIT, LIST, CREATE]
           EDITOR:   [OPERATOR, EXPORT]
           ADMIN:    [MASTER]
           PUBLISHER: [PUBLISH]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER, PUBLISH]
    title:      Networking CMS
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        layout:  NetworkingInitCmsBundle::admin_layout.html.twig
        ajax:    NetworkingInitCmsBundle::ajax_layout.html.twig
        list:    NetworkingInitCmsBundle:CRUD:list.html.twig
        show:    NetworkingInitCmsBundle:CRUD:show.html.twig
        edit:    NetworkingInitCmsBundle:CRUD:edit.html.twig
        preview: NetworkingInitCmsBundle:CRUD:preview.html.twig
        delete:  NetworkingInitCmsBundle:CRUD:delete.html.twig
        # default values of helper templates
        short_object_description: NetworkingInitCmsBundle:Helper:short-object-description.html.twig
        # default values of block templates, they should extend the base_block template
        list_block: NetworkingInitCmsBundle:Block:block_admin_list.html.twig
    dashboard:
        blocks:
            # display two dashboard blocks
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [Pages, Media] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [Config, Users] } }

        groups:
            Pages:
                label: Pages
                items: [networking_init_cms.page.admin.page, networking_init_cms.menu.admin.menu_item]
            Media:
                label: Media
                items: [sonata.media.admin.media, sonata.media.admin.gallery, networking_init_cms.page.admin.tag]
            Config:
                label: Config
                items: [networking_init_cms.page.admin.help_text]
            Users:
                label: Users
                items: [sonata.user.admin.user, sonata.user.admin.group ]
#            News:
#                label: News
#                items: [networking_cms.news.admin.article]

sonata_doctrine_orm_admin:
    templates:
        form: [ NetworkingInitCmsBundle:Form:form_admin_fields.html.twig ]
        types:
            list:
                array:      NetworkingInitCmsBundle:CRUD:list_array.html.twig
                boolean:    NetworkingInitCmsBundle:CRUD:list_boolean.html.twig
                date:       NetworkingInitCmsBundle:CRUD:list_date.html.twig
                time:       NetworkingInitCmsBundle:CRUD:list_time.html.twig
                datetime:   NetworkingInitCmsBundle:CRUD:list_datetime.html.twig
                text:       NetworkingInitCmsBundle:CRUD:base_list_field.html.twig
                trans:      NetworkingInitCmsBundle:CRUD:list_trans.html.twig
                string:     NetworkingInitCmsBundle:CRUD:base_list_field.html.twig
                smallint:   NetworkingInitCmsBundle:CRUD:base_list_field.html.twig
                bigint:     NetworkingInitCmsBundle:CRUD:base_list_field.html.twig
                integer:    NetworkingInitCmsBundle:CRUD:base_list_field.html.twig
                decimal:    NetworkingInitCmsBundle:CRUD:base_list_field.html.twig
                identifier: NetworkingInitCmsBundle:CRUD:base_list_field.html.twig

            show:
                array:      NetworkingInitCmsBundle:CRUD:show_array.html.twig
                boolean:    NetworkingInitCmsBundle:CRUD:show_boolean.html.twig
                date:       NetworkingInitCmsBundle:CRUD:show_date.html.twig
                time:       NetworkingInitCmsBundle:CRUD:show_time.html.twig
                datetime:   NetworkingInitCmsBundle:CRUD:show_datetime.html.twig
                text:       NetworkingInitCmsBundle:CRUD:base_show_field.html.twig
                trans:      NetworkingInitCmsBundle:CRUD:show_trans.html.twig
                string:     NetworkingInitCmsBundle:CRUD:base_show_field.html.twig
                smallint:   NetworkingInitCmsBundle:CRUD:base_show_field.html.twig
                bigint:     NetworkingInitCmsBundle:CRUD:base_show_field.html.twig
                integer:    NetworkingInitCmsBundle:CRUD:base_show_field.html.twig
                decimal:    NetworkingInitCmsBundle:CRUD:base_show_field.html.twig
                birthday:       NetworkingInitCmsBundle:CRUD:show_date.html.twig