sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
           GUEST:    [VIEW, LIST]
           STAFF:    [EDIT, LIST, CREATE]
           EDITOR:   [OPERATOR, EXPORT]
           ADMIN:    [MASTER]
           PUBLISHER: [PUBLISH]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER, PUBLISH]
    title:      Networking CMS
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        layout:  NetworkingInitCmsBundle::admin_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        list:    NetworkingInitCmsBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    NetworkingInitCmsBundle:CRUD:edit.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        delete:  NetworkingInitCmsBundle:CRUD:delete.html.twig
        # default values of helper templates
        short_object_description: SonataAdminBundle:Helper:short-object-description.html.twig
        # default values of block templates, they should extend the base_block template
        list_block: SonataAdminBundle:Block:block_admin_list.html.twig
    dashboard:
        blocks:
            # display two dashboard blocks
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [Pages] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [Media, Users] } }

        groups:
            Pages:
                label: Pages
                items: [networking_init_cms.page.admin.page, networking_init_cms.menu.admin.menu_item, networking_init_cms.page.admin.tag]
            Media:
                label: Media
                items: [sonata.media.admin.media, sonata.media.admin.gallery]
            Users:
                label: Users
                items: [sonata.user.admin.user, sonata.user.admin.group ]
#            News:
#                label: News
#                items: [networking_cms.news.admin.article]

sonata_doctrine_orm_admin:
    templates:
        form: [ NetworkingInitCmsBundle:Form:form_admin_fields.html.twig ]