imports:
    - { resource: @NetworkingInitCmsBundle/Resources/config/assetic.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/doctrine.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/fos_user.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/security_config.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/sonata_admin.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/sonata_block.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/sonata_media.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/sonata_user.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/stof_doctrine_extensions.yml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/symfony_cmf_routing_extra.yml }
#    - { resource: @ApplicationSonataMediaBundle/Resources/config/doctrine_orm_admin.xml }
    - { resource: @NetworkingInitCmsBundle/Resources/config/mopa_bootstrap.yml }
    - { resource: @MopaRemoteUpdateBundle/Resources/config/config.yml }

