services:
# Page Admin Contoller
    networking_init_cms.admin.helper:
        class: Networking\InitCmsBundle\Admin\AdminHelper
        arguments:
            - @sonata.admin.pool

    networking_init_cms.page.admin.page:
        class: Networking\InitCmsBundle\Admin\PageAdmin
        arguments: [null, Application\Networking\InitCmsBundle\Entity\Page, NetworkingInitCmsBundle:PageAdmin]
        calls:
            - [setTranslationDomain, [PageAdmin]]
            - [setLanguages, [%networking_init_cms.page.languages%]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pages, label_translator_strategy: sonata.admin.label.strategy.underscore, persist_filters: true }

# Tag Admin Controller
    networking_init_cms.page.admin.tag:
        class: Networking\InitCmsBundle\Admin\TagAdmin
        arguments: [null, Networking\InitCmsBundle\Entity\Tag, NetworkingInitCmsBundle:CRUD]
        calls:
            - [setTranslationDomain, [TagAdmin]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tags, label_translator_strategy: sonata.admin.label.strategy.underscore}

# HelpText Admin Controller
    networking_init_cms.page.admin.help_text:
        class: Networking\InitCmsBundle\Admin\HelpTextAdmin
        arguments: [null, Networking\InitCmsBundle\Entity\HelpText, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, [HelpTextAdmin]]
            - [setLanguages, [%networking_init_cms.page.languages%]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Help Text', label_translator_strategy: sonata.admin.label.strategy.underscore}


# Layout Block Admin Controller
    networking_init_cms.page.admin.layout_block:
        class: Networking\InitCmsBundle\Admin\LayoutBlockAdmin
        arguments: [null, Networking\InitCmsBundle\Entity\LayoutBlock, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, [PageAdmin]]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Content, label_translator_strategy: sonata.admin.label.strategy.underscore }

# Menu Admin Controller
    networking_init_cms.menu.admin.menu_item:
        class: Networking\InitCmsBundle\Admin\MenuItemAdmin
        arguments: [null, Networking\InitCmsBundle\Entity\MenuItem, NetworkingInitCmsBundle:MenuItemAdmin]
        calls:
            - [setTranslationDomain, [MenuItemAdmin]]
            - [setLanguages, [%networking_init_cms.page.languages%]]
            - [setSubClasses, [{"menu": Networking\InitCmsBundle\Entity\MenuItem, "menu item": Networking\InitCmsBundle\Entity\MenuItem}]]
        tags:
            - { name: sonata.admin, manager_type: orm, icon: happy, label: "Menus", label_translator_strategy: sonata.admin.label.strategy.underscore}
