parameters:
# MEDIA
    sonata.media.admin.media.class: Networking\InitCmsBundle\Admin\Entity\MediaAdmin
    sonata.media.admin.media.controller: NetworkingInitCmsBundle:MediaAdmin
    sonata.media.admin.media.translation_domain: MediaAdmin

# GALLERY
    sonata.media.admin.gallery.class: Networking\InitCmsBundle\Admin\GalleryAdmin
    sonata.media.admin.gallery.controller: NetworkingInitCmsBundle:GalleryAdmin
    sonata.media.admin.gallery.translation_domain: %sonata.media.admin.media.translation_domain%

# User
    sonata.user.admin.groupname: sonata_user

services:
# Translation Admin
    ibrows_sonata_translation.admin.orm:
        class: Networking\InitCmsBundle\Admin\Entity\TranslationAdmin
        arguments: [null, Lexik\Bundle\TranslationBundle\Entity\TransUnit, IbrowsSonataTranslationBundle:TranslationCRUD]
        calls:
            - [setEditableOptions, [%ibrows_sonata_translation.editable%]]
            - [setTranslationDomain, [IbrowsSonataTranslationBundle]]
            - [setTransUnitManager, [@lexik_translation.trans_unit.manager]]
            - [setManagedLocales, [%lexik_translation.managed_locales%]]
        tags:
            - { name: sonata.admin, manager_type: orm, icon: happy, group: group.translation,  label: "translation.title", label_catalogue: "IbrowsSonataTranslationBundle"}

# Media Admin
    sonata.media.admin.media:
        class: %sonata.media.admin.media.class%
        arguments: [null, %sonata.media.admin.media.entity%, %sonata.media.admin.media.controller%, @sonata.media.pool]
        calls:
            - [setModelManager, [@sonata.media.admin.media.manager]]
            - [setTranslationDomain, [%sonata.media.admin.media.translation_domain%]]
            - [setLanguages, [%networking_init_cms.page.languages%]]
            - [setTemplates, [{ layout: "NetworkingInitCmsBundle::admin_layout.html.twig", ajax: "NetworkingInitCmsBundle::ajax_layout.html.twig", edit: NetworkingInitCmsBundle:CRUD:edit.html.twig, show:" NetworkingInitCmsBundle:CRUD:show.html.twig", list: "NetworkingInitCmsBundle:MediaAdmin:list.html.twig" }]]
        tags:
            - { name: sonata.admin, manager_type: orm, icon: happy, group: sonata_media,  label: "Media", label_catalogue: %sonata.media.admin.media.translation_domain%, label_translator_strategy: "sonata.admin.label.strategy.underscore"}


# Gallery Admin
    sonata.media.admin.gallery:
        class: %sonata.media.admin.gallery.class%
        arguments: [null, %sonata.media.admin.gallery.entity%, %sonata.media.admin.gallery.controller%, @sonata.media.pool]
        calls:
            - [setTranslationDomain, [%sonata.media.admin.gallery.translation_domain%]]
            - [setTemplates, [{ layout: "NetworkingInitCmsBundle::admin_layout.html.twig", ajax: "NetworkingInitCmsBundle::ajax_layout.html.twig", edit: NetworkingInitCmsBundle:CRUD:edit.html.twig, show:" NetworkingInitCmsBundle:CRUD:show.html.twig", list: "NetworkingInitCmsBundle:MediaAdmin:list.html.twig" }]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_media,  label: "Gallery", label_catalogue: %sonata.media.admin.gallery.translation_domain%, label_translator_strategy: "sonata.admin.label.strategy.underscore"}


# User Admin
    sonata.user.admin.user:
        class: %sonata.user.admin.user.class%
        arguments: [null, %sonata.user.admin.user.entity%, %sonata.user.admin.user.controller%]
        calls:
            - [setUserManager, [@fos_user.user_manager]]
            - [setTranslationDomain, [%sonata.user.admin.user.translation_domain%]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: %sonata.user.admin.groupname%",  label: "users", label_catalogue: SonataUserBundle, label_translator_strategy: "sonata.admin.label.strategy.underscore"}


# Group Admin
    sonata.user.admin.group:
        class: %sonata.user.admin.group.class%
        arguments: [null, %sonata.user.admin.group.entity%, %sonata.user.admin.group.controller%]
        calls:
            - [setTranslationDomain, [%sonata.user.admin.group.translation_domain%]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: %sonata.user.admin.groupname%",  label: "groups", label_catalogue: SonataUserBundle, label_translator_strategy: "sonata.admin.label.strategy.underscore"}
