services:
    networking_init_cms.page_class_meta:
        class: Doctrine\ODM\MongoDB\Mapping\ClassMetadata
        arguments: [ Application\Networking\InitCmsBundle\Document\Page ]

    networking_init_cms.page_repository:
        class: Networking\InitCmsBundle\Docment\PageManager
        arguments: [ @doctrine_mongodb.odm.document_manager, @networking_init_cms.page_class_meta ]
        calls:
          - [ setContainer, [ @service_container] ]