language: php

php:
  - 7.0

# Update composer
before-install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - php -i | grep memory_limit
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install