networking_init_cms:
    admin_toolbar: ~
    translation_fallback_route: 'initcms_no_translation'
    no_translation_template: 'NetworkingInitCmsBundle::no_translation_found.html.twig'
    404_template: 'NetworkingInitCmsBundle::error_404.html.twig'
    languages:
        - {label: English, locale: en_US}
    content_types:
        - { name: 'Text' , class: 'Networking\InitCmsBundle\Entity\Text'}
        - { name: 'Gallery' , class: 'Networking\GalleryBundle\Entity\Gallery'}
    admin_menu_groups:
        big:
          items: [pages, menu, media]
        small:
          items: [users, help_text, translation]
