Networking\InitCmsBundle\Entity\GalleryView:
    properties:
        id:
            type: integer
        layoutBlock:
            exclude: true
        mediaGallery:
            type: Networking\InitCmsBundle\Entity\Gallery
        gallery_type:
            type: string
        createdAt:
            type: DateTime
        updatedAt:
            type: DateTime