Networking\InitCmsBundle\Entity\BaseText:
    properties:
        id:
            type: integer
        layoutBlock:
            exclude: true
        text:
            type: string
        createdAt:
            type: DateTime
        updatedAt:
            type: DateTime