Networking\InitCmsBundle\Model\Text:
    properties:
        id:
            type: integer
        createdAt:
            type: DateTime
        updatedAt:
            type: DateTime
        text:
            type: string