Networking\InitCmsBundle\Entity\BaseText:
  type: mappedSuperclass
  fields:
    text:
      type: text
      nullable: true
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
  lifecycleCallbacks:
    prePersist: [ prePersist ]
    preUpdate: [ preUpdate ]

